### ISSUE TITLE
Align spending data graph goals with filter changes (or vice versa)

### ISSUE THREAD

**Issue by daisypjm** [pat-shannon/mean-money#119]
### Feature

Dashboard

### Suggested Priority

Medium

### Observed Behaviour

The filters allow for the user to select any 2 dates, potentially spanning a wide time frame of spending data. However the monthly goal (understandably) is always the same and shows only monthly goals. This means users can end up comparing their entire payment history against a single monthly budget.

Could we get the two to align? Perhaps the easier solution would be to limit the filters so that they only allow a single month of spending data to be viewed at a time?

Alternatively we could try to update the monthly goals so that they match the time period, but this seems more fiddly!

### Expected Behaviour

When a user filters their spending graph, the chart shows both actual and goal spending for that time period. Either by limiting the filters to only ever span a month, or by adjusting the graph to reflect the start and end date filters.

### Reproduction Steps

1. Log in and navigate to the dashboard
2. Filter the spending data using a start date of 01/05/1500, and an end date of 01/05/3000 and submit
3. Spending goals will continue to reflect monthly amounts

<img width="991" alt="Screenshot 2024-12-18 at 16 50 14" src="https://github.com/user-attachments/assets/4276cc34-d386-42b0-bba3-998f5073d4df" />

**Comment by pat-shannon** [comment]
Not sure if that's the best way of doing it - the current system, by default, shows the user their spending within the current month against the overall month goal. I think it makes it easier to keep track of things by thinking of things month by month. If a user did their weekly shop 2 days into the month and the graph showed the user that they're 3x over budget because we're averaging their spending goal across each day, I don't think that's a particularly helpful way of showing things as opposed to them being shown through the graph that they're, for example, 1/4 of the way to their monthly spending goal.

Don't know if limiting the user to month by month is the right solution either, as this limits the user's options, preventing them from seeing, for example, if they spent a particularly high amount in one week relative to their monthly goals, or viewing a ~30 day period that isn't one of the 12 months in a year (e.g. the last 30 days from the current date).

Obviously exclusively showing the goals for a month long period regardless of the time period selected isn't perfect, but I personally am not sure there's a better alternative we could implement given the scope of the project.

**Comment by daisypjm** [comment]
Thanks a lot for this - both perspectives make complete sense and I think you're right, a good solution would require much more thought and work than we can achieve in this time frame.

I'll deprioritise this and close the ticket. We can include it in our QE presentation as it's an interesting discussion point around data visualisation/user experience.
